PROJECT_NAME := {{cookiecutter.app_name|replace(' ', '\\ ')}}
COIN_PATH    := {{cookiecutter.coin_path}}
BIP32_KEY    := {{cookiecutter.bip32_key}}

APP_VERSION_MAJOR := 0
APP_VERSION_MINOR := 0
APP_VERSION_PATCH := 0

include jolt_wallet/make/app.mk
